# Student Placement Data Analysis Using SQL

## Problem Statement
Colleges maintain student academic, skill and placement data.
Analyzing this data can help understand placement performance,
salary trends and factors associated with student placements.

## Objective
To use SQL to analyze student placement data and identify
useful placement-related insights.

In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect('placement.db')

cursor = conn.cursor()

print("Database created successfully!")

Database created successfully!

In [3]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    Student_ID INTEGER PRIMARY KEY,
    Name TEXT,
    Department TEXT,
    CGPA REAL,
    Python_Skill INTEGER,
    SQL_Skill INTEGER,
    Projects INTEGER,
    Placement_Status TEXT,
    Salary_LPA REAL
)
""")

conn.commit()

print("Students table created successfully!")

Students table created successfully!

In [4]:
students_data = [
    (101, 'Aarav', 'AI & DS', 8.5, 8, 7, 4, 'Placed', 12.0),
    (102, 'Diya', 'CSE', 9.1, 9, 9, 5, 'Placed', 15.0),
    (103, 'Kavin', 'AI & DS', 7.4, 6, 5, 2, 'Not Placed', 0),
    (104, 'Meera', 'CSE', 8.8, 8, 9, 4, 'Placed', 13.5),
    (105, 'Rahul', 'ECE', 7.2, 5, 6, 2, 'Not Placed', 0),
    (106, 'Nila', 'AI & DS', 9.3, 9, 8, 5, 'Placed', 16.0),
    (107, 'Vikram', 'ECE', 8.0, 7, 7, 3, 'Placed', 8.5),
    (108, 'Ananya', 'CSE', 7.8, 7, 8, 3, 'Placed', 9.0),
    (109, 'Surya', 'AI & DS', 6.9, 5, 5, 1, 'Not Placed', 0),
    (110, 'Ishita', 'CSE', 8.6, 8, 8, 4, 'Placed', 11.5),
    (111, 'Arjun', 'ECE', 7.6, 6, 7, 2, 'Not Placed', 0),
    (112, 'Priya', 'AI & DS', 8.9, 9, 9, 5, 'Placed', 14.0)
]

cursor.executemany("""
INSERT OR REPLACE INTO students
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
""", students_data)

conn.commit()

print("Student data inserted successfully!")

Student data inserted successfully!

In [5]:
query = """
SELECT *
FROM students;
"""

df_students = pd.read_sql_query(query, conn)

df_students

,Student_ID,Name,Department,CGPA,Python_Skill,SQL_Skill,Projects,Placement_Status,Salary_LPA
0,101,Aarav,AI & DS,8.5,8,7,4,Placed,12.0
1,102,Diya,CSE,9.1,9,9,5,Placed,15.0
2,103,Kavin,AI & DS,7.4,6,5,2,Not Placed,0.0
3,104,Meera,CSE,8.8,8,9,4,Placed,13.5
4,105,Rahul,ECE,7.2,5,6,2,Not Placed,0.0
5,106,Nila,AI & DS,9.3,9,8,5,Placed,16.0
6,107,Vikram,ECE,8.0,7,7,3,Placed,8.5
7,108,Ananya,CSE,7.8,7,8,3,Placed,9.0
8,109,Surya,AI & DS,6.9,5,5,1,Not Placed,0.0
9,110,Ishita,CSE,8.6,8,8,4,Placed,11.5
10,111,Arjun,ECE,7.6,6,7,2,Not Placed,0.0
11,112,Priya,AI & DS,8.9,9,9,5,Placed,14.0

In [7]:
query = """
SELECT *
FROM students
WHERE Placement_Status = 'Placed';
"""

placed_students = pd.read_sql_query(query, conn)

placed_students

,Student_ID,Name,Department,CGPA,Python_Skill,SQL_Skill,Projects,Placement_Status,Salary_LPA
0,101,Aarav,AI & DS,8.5,8,7,4,Placed,12.0
1,102,Diya,CSE,9.1,9,9,5,Placed,15.0
2,104,Meera,CSE,8.8,8,9,4,Placed,13.5
3,106,Nila,AI & DS,9.3,9,8,5,Placed,16.0
4,107,Vikram,ECE,8.0,7,7,3,Placed,8.5
5,108,Ananya,CSE,7.8,7,8,3,Placed,9.0
6,110,Ishita,CSE,8.6,8,8,4,Placed,11.5
7,112,Priya,AI & DS,8.9,9,9,5,Placed,14.0

In [8]:
query = """
SELECT Name, Department, CGPA
FROM students
WHERE CGPA > 8;
"""

high_cgpa_students = pd.read_sql_query(query, conn)

high_cgpa_students

     Name Department  CGPA
0   Aarav    AI & DS   8.5
1    Diya        CSE   9.1
2   Meera        CSE   8.8
3    Nila    AI & DS   9.3
4  Ishita        CSE   8.6
5   Priya    AI & DS   8.9

In [9]:
query = """
SELECT Name, Department, CGPA
FROM students
ORDER BY CGPA DESC;
"""

result = pd.read_sql_query(query, conn)

result

      Name Department  CGPA
0     Nila    AI & DS   9.3
1     Diya        CSE   9.1
2    Priya    AI & DS   8.9
3    Meera        CSE   8.8
4   Ishita        CSE   8.6
5    Aarav    AI & DS   8.5
6   Vikram        ECE   8.0
7   Ananya        CSE   7.8
8    Arjun        ECE   7.6
9    Kavin    AI & DS   7.4
10   Rahul        ECE   7.2
11   Surya    AI & DS   6.9

In [10]:
query = """
SELECT Name, Department, CGPA
FROM students
ORDER BY CGPA DESC
LIMIT 3;
"""

top_students = pd.read_sql_query(query, conn)

top_students

    Name Department  CGPA
0   Nila    AI & DS   9.3
1   Diya        CSE   9.1
2  Priya    AI & DS   8.9

In [11]:
query = """
SELECT Name, Department, CGPA, Salary_LPA
FROM students
WHERE Placement_Status = 'Placed'
ORDER BY Salary_LPA DESC
LIMIT 5;
"""

top_packages = pd.read_sql_query(query, conn)

top_packages

    Name Department  CGPA  Salary_LPA
0   Nila    AI & DS   9.3        16.0
1   Diya        CSE   9.1        15.0
2  Priya    AI & DS   8.9        14.0
3  Meera        CSE   8.8        13.5
4  Aarav    AI & DS   8.5        12.0

In [12]:
query = """
SELECT COUNT(*) AS Total_Students
FROM students;
"""

result = pd.read_sql_query(query, conn)
result

   Total_Students
0              12

In [13]:
query = """
SELECT AVG(CGPA) AS Average_CGPA
FROM students;
"""

result = pd.read_sql_query(query, conn)
result

   Average_CGPA
0         8.175

In [14]:
query = """
SELECT MAX(Salary_LPA) AS Highest_Package
FROM students;
"""

result = pd.read_sql_query(query, conn)
result

   Highest_Package
0             16.0

In [15]:
query = """
SELECT MIN(Salary_LPA) AS Lowest_Placed_Package
FROM students
WHERE Placement_Status = 'Placed';
"""

result = pd.read_sql_query(query, conn)
result

   Lowest_Placed_Package
0                    8.5

In [16]:
query = """
SELECT Department,
       AVG(CGPA) AS Average_CGPA
FROM students
GROUP BY Department;
"""

department_cgpa = pd.read_sql_query(query, conn)

department_cgpa

  Department  Average_CGPA
0    AI & DS         8.200
1        CSE         8.575
2        ECE         7.600

In [17]:
query = """
SELECT Department,
       COUNT(*) AS Placed_Students
FROM students
WHERE Placement_Status = 'Placed'
GROUP BY Department;
"""

department_placements = pd.read_sql_query(query, conn)

department_placements

  Department  Placed_Students
0    AI & DS                3
1        CSE                4
2        ECE                1

In [18]:
query = """
SELECT Department,
       ROUND(AVG(Salary_LPA), 2) AS Average_Salary_LPA
FROM students
WHERE Placement_Status = 'Placed'
GROUP BY Department
ORDER BY Average_Salary_LPA DESC;
"""

department_salary = pd.read_sql_query(query, conn)

department_salary

  Department  Average_Salary_LPA
0    AI & DS               14.00
1        CSE               12.25
2        ECE                8.50

In [19]:
query = """
SELECT Placement_Status,
       COUNT(*) AS Number_of_Students
FROM students
GROUP BY Placement_Status;
"""

placement_summary = pd.read_sql_query(query, conn)

placement_summary

  Placement_Status  Number_of_Students
0       Not Placed                   4
1           Placed                   8

In [20]:
query = """
SELECT Department,
       ROUND(AVG(CGPA), 2) AS Average_CGPA
FROM students
GROUP BY Department
HAVING AVG(CGPA) > 8;
"""

result = pd.read_sql_query(query, conn)
result

  Department  Average_CGPA
0    AI & DS          8.20
1        CSE          8.57

In [21]:
query = """
SELECT Name,
       CGPA,
       CASE
           WHEN CGPA >= 9 THEN 'Excellent'
           WHEN CGPA >= 8 THEN 'Good'
           WHEN CGPA >= 7 THEN 'Average'
           ELSE 'Needs Improvement'
       END AS CGPA_Category
FROM students;
"""

cgpa_category = pd.read_sql_query(query, conn)
cgpa_category

      Name  CGPA      CGPA_Category
0    Aarav   8.5               Good
1     Diya   9.1          Excellent
2    Kavin   7.4            Average
3    Meera   8.8               Good
4    Rahul   7.2            Average
5     Nila   9.3          Excellent
6   Vikram   8.0               Good
7   Ananya   7.8            Average
8    Surya   6.9  Needs Improvement
9   Ishita   8.6               Good
10   Arjun   7.6            Average
11   Priya   8.9               Good

In [22]:
query = """
SELECT
    ROUND(
        100.0 * SUM(CASE WHEN Placement_Status = 'Placed' THEN 1 ELSE 0 END)
        / COUNT(*), 2
    ) AS Placement_Percentage
FROM students;
"""

placement_percentage = pd.read_sql_query(query, conn)

placement_percentage

   Placement_Percentage
0                 66.67

In [23]:
query = """
SELECT
    Placement_Status,
    ROUND(AVG(Python_Skill), 2) AS Avg_Python_Skill,
    ROUND(AVG(SQL_Skill), 2) AS Avg_SQL_Skill,
    ROUND(AVG(Projects), 2) AS Avg_Projects
FROM students
GROUP BY Placement_Status;
"""

skill_analysis = pd.read_sql_query(query, conn)

skill_analysis

  Placement_Status  Avg_Python_Skill  Avg_SQL_Skill  Avg_Projects
0       Not Placed              5.50           5.75          1.75
1           Placed              8.13           8.13          4.13

In [24]:
query = """
SELECT
    Name,
    Department,
    CGPA,
    Salary_LPA
FROM students
WHERE Placement_Status = 'Placed'
ORDER BY Salary_LPA DESC
LIMIT 1;
"""

highest_paid = pd.read_sql_query(query, conn)

highest_paid

   Name Department  CGPA  Salary_LPA
0  Nila    AI & DS   9.3        16.0

## Key Insights

1. The dataset contains 12 students across AI & DS, CSE and ECE departments.
2. 8 out of 12 students were placed, giving a placement percentage of 66.67%.
3. The highest placement package was 16 LPA.
4. Nila received the highest package of 16 LPA.
5. SQL helped analyze placement status, salary, CGPA, skills and department-wise performance.
6. Skill analysis allowed comparison of Python, SQL and project scores between placed and non-placed students.

In [25]:
conn.commit()

print("Database saved successfully!")

Database saved successfully!